### ISSUE TITLE
Default values for attributes?

### ISSUE THREAD

**Issue by PaBLoX-CL** [lotus/utils#68]
I was using `lotus/validations` in my gem, I liked the syntax sugar of `attribute`, with their validations. But I found out that there's no way to include default data. It seems (to me at least) something basic, so maybe I'm just missing something obvious (I read the _verbose_ explanation on how to use **only** the validations, but using that I have to sacrifice almost all the sugar).

Is there already a way to do it?

**Comment by joneslee85** [comment]
@PaBLoX-CL can you please post it on `lotus/validations` repo?

**Comment by PaBLoX-CL** [comment]
Sure, sorry, when I posted this I thought was an attribute created trough `lotus/utils`, but after peeking at the source code I realize it was in the validations repo :P.
