### ISSUE TITLE
Interactor: recording error shouldn't return false?

### ISSUE THREAD

**Issue by luislavena** [lotus/utils#69]
Hello,

Been playing with `Lotus::Interactor` and trying to combine `valid?` requirement (since is a private method that **must** override) with logging of `errors`, and found that `error` logging is not returning a false/falsy value to be used in combination with `valid?`.

Example:

```ruby
class PublishVideo < Struct.new(:user, :video)
  include Lotus::Interactor

  def call
    puts "publish!"
    puts "reindex!"
  end

  def valid?
    owns? && non_published?
  end

  private

  def owns?
    # trivial ownership check
    (video.user_id == user.id) or
      error "You're not owner of this video"
  end

  def non_published?
    video.draft? or
      error "Can only publish a draft video"
  end
end
```

Problem is that `valid?` returns `true`, even when `error` has been called and `errors` is not empty:

```ruby
class User < Struct.new(:id)
end

class Video < Struct.new(:user_id, :draft)
  alias_method :draft?, :draft
end

user  = User.new(1)
video = Video.new(2, false)

service = PublishVideo.new(user, video)
result  = service.call

p success: result.success?,  # => false
  errors:  result.errors     # => ["You're not owner of this video", "Can only publish a draft video"]
```

Perhaps I'm misusing Interactor in this case?

Any hint will be appreciated.

Thank you.

**Comment by AlfonsoUceda** [comment]
In this example `valid?` returns:
```ruby
service.valid?
#  => ["You're not owner of this video", "Can only publish a draft video"]
```
now `valid?` is returning errors, should check errors array, I think this is a bug

**Comment by jodosha** [comment]
@luislavena @AlfonsoUceda Hello and sorry for the delayed reply, I've been busy with day job and then took a few days off. I've opened a PR (#70) to fix this problem. Would you like to review it and check if it solves your problem?

@luislavena This Interactor usage is new to me, but yeah it makes sense to return _falsey_ for `#error`. In general you should check the returning value of `#call`:

```ruby
result = PublishVideo.new(user, video).call
result.success? # => true or false
```

This is the reason why `#valid?` is private.

**Comment by luislavena** [comment]
@jodosha made `valid?` public just to expose the issue, but the problem is that `call` is invoked.

From my example:

```ruby
p success: result.success?,  # => false
  errors:  result.errors     # => ["You're not owner of this video", "Can only publish a draft video"]
```

While `success?` returns `false`, the code inside `call` is invoked:

```console
publish!
reindex!
{:success=>false, :errors=>["You're not owner of this video", "Can only publish a draft video"]}
```

That is caused by `valid?` not returning a *falsey* value.

I've workaround this by implementing the logic checks like the following:

```ruby
  def owns?
    return true if (video.user_id == user.id)

    error "You're not owner of this video"
    false
  end
```

As you can see, not easy to follow :smile: 

Will look into the PR shortly, I might have more feedback in relation to the Interactor, but as you, day job takes priority :smile: 

Thanks again for your responses, fixes and the tools itself!

:heart: :heart: :heart:
