### ISSUE TITLE
Interactor: introduce `expose` to replace automagic instance variable collection

### ISSUE THREAD

**Issue by luislavena** [lotus/utils#77]
Hello,

Once again, thanks you all for the great work on Lotus!

At some point on Gitter I mention replace the automagical instance variable conversion to mimic `Lotus::Action` `expose` behavior:

```ruby
class SignIn < Struct.new(:params)
  include Lotus::Interactor

  expose :user

  def call
    @user = User.find params[:id]
  end
end

result = SignIn.new({ id: 15 }).call
result.exposures # => { user: <User:0x007f965c1d0318 @id=15> }
result.user # => <User:0x007f965c1d0318 @id=15>
```

The only difference will be the direct mapping as methods between exposures (as part of payload).

I've a patch for this locally, but I'm concern about the change in behavior, which is why I'm submitting this question first:

Should I keep current behavior (expose all instance variables) *unless* `expose` is used? That way existing code will not break.

What would be the proper approach to handle such scenario?

Looking forward your feedback.

Thank you.

**Comment by AlfonsoUceda** [comment]
Hi @luislavena 

Nice feature but in which scenarios do you use this feature? This `expose` api only add visibility to know what instance variables you exposed, somethin like public and private instance variables.

**Comment by luislavena** [comment]
That is correct.

We use several instance variables that should remain private to the
service, for example memoize an api call.

We would like to decide what to expose instead of the arbitrary *all
instance variables* without having to use special naming.

Having a defined exposure also helps with the contract for the service.

Thank you.

Sorry for top posting. Sent from mobile.

**Comment by AlfonsoUceda** [comment]
@jodosha I agree with @luislavena I created several "interactors/services" in rails (without gem) and some times I use memoization and I only expose some instance variables.

What do you think to support this feature?

**Comment by jodosha** [comment]
@luislavena Thanks for brining this discussion on the table. My reply comes a bit later because of the 0.3.1 release of `lotusrb`. I'm totally :+1: with this, but because it's a breaking change, I'd bump `lotus-utils` 0.5.0.

**Comment by AlfonsoUceda** [comment]
@jodosha @luislavena told us this
```
Should I keep current behavior (expose all instance variables) unless expose is used? That way existing code will not break.
```

**Comment by AlfonsoUceda** [comment]
@luislavena can you make a PR with this new feature? thanks ;)

**Comment by joneslee85** [comment]
I like this idea too, :+1:

**Comment by luislavena** [comment]
@AlfonsoUceda @joneslee85 great, will send the pull request shortly! (just back from some time off :smile: :sunny:)

**Comment by jodosha** [comment]
@luislavena PING. I would love to include this change in v0.5.0, which will be a dependency for Lotus v0.4.0 (June 23rd). Do you will have time to work on this?

**Comment by luislavena** [comment]
Yeah!

I'm traveling right now but will send my pull request this weekend.

**Comment by jodosha** [comment]
@luislavena I took this over, as we have so little time to wrap up this release. Would you mind to review? Thank you! #80

**Comment by luislavena** [comment]
@jodosha sorry, had a few setbacks on my flights and limited internet over the past few days.

Checking your changes now, thank you.

**Comment by jodosha** [comment]
@luislavena No worries, just wanted to avoid to rush for this change one or two days before the release.
