### ISSUE TITLE
Release version 0.6

### ISSUE THREAD

**Issue by DanielBlanco** [lotus/utils#91]
Hi Lotus has a dependency on Lotus Utils version 0.6 https://github.com/lotus/lotus/blob/master/lotusrb.gemspec#L22

But Gem Version is currently: [![Gem Version](http://img.shields.io/gem/v/lotus-utils.svg)](https://badge.fury.io/rb/lotus-utils)

Can you please release 0.6?

**Comment by jodosha** [comment]
@DanielBlanco `lotus-utils` 0.6 will be released when `lotusrb` will hit 0.6.

I think you're using `lotusrb` master if you're asking this question :wink: If so, please add this line to your `Gemfile`.

```ruby
gem 'lotus-utils', github: 'lotus/utils', branch: '0.6.x'
```
